# Generated by Django 3.2.15 on 2022-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001C961DAD310>', max_length=200),
        ),
    ]
