# Generated by Django 3.2.15 on 2022-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000210CCA3C4C0>', max_length=200),
        ),
    ]
